name: One-Click Build (DLL & App)

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Forces the runner to use the 32-bit compiler
      - name: Setup MinGW 32-bit
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: 'win32_mingw81'
          
      - name: Build Wrapper DLL
        run: |
          cd j2534_OverIP
          qmake j2534_OverIP.pro
          mingw32-make release
          
      - name: Build GUI App
        run: |
          cd j2534_OverIP_App
          qmake j2534_OverIP_App.pro
          mingw32-make release
          
      - name: Upload Compiled Files
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-J2534-Windows
          path: |
            j2534_OverIP/release/*.dll
            j2534_OverIP_App/release/*.exe
